const projects = [
	{	id					: 1, 
		title				: "Multi-Disciplinary Capstone",
		images				: ["images/liscena.png"],
		date 				: "Sept 2018 - April 2019",
		short_description	: "Creating an Intelligent Insurance Claims Bot", 
		long_description	: "<h2>Creating an Intelligent Insurance Claims Bot</h2><p> As part of our final year capstone project, I worked on a multidisciplinary capstone project along with 4 other engineering students. In this project, we worked along side <a href=‘www.liscena.com’>Liscena</a>, a startup founded by two of the team members. The goal of the project was to improve the insurance claims process by digitizing, automating, and adding intelligence to the initial claims filing cycle, and subsequent follow up. The team collected requirements for the project, brainstormed and designed a solution that took the very complicated First Notice of Loss (FNOL) process and represented it as a chatbot-like implementation, with a heavy focus on user experience.</p><p> Because we were working alongside a startup, there was a lot of flexibility in the design decisions able to be made in building up the infrastructure of the product. I had an opportunity to flex not only my technical implementation skills, but my software design skills, balancing current goals  of the project while continuing to consider future improvements, and integrations. In addition to various front-end tasks, and simple feature implementation tasks, I worked on designing the initial database schema to store all required data for the various aspects of the products, in addition to designing a schema and parser for encoding and decoding complicated logical statements from a human-readable state to a computer parse-able state.</p><p>One important lesson learned from this project is learning to question all assumptions made, and taking into careful consideration what drives value to clients, instead of just trying to make the coolest and exciting product</p><p> As well, since this was part of the Capstone course, there were many documents that were created, starting from collecting requirements and analyzing a business process diagram, to ideation, evaluation of a design, and writing a final report. </p><p> <strong>Skills Developed: </strong> Database Design, JS, AWS, Engineering Report Writing</p> "
	},
	{	id					: 2, 
		title				: "Undergraduate Thesis",
		images				: ["images/thesis.png"],
		date 				: "Sept 2018 - April 2019",
		short_description	: "Neural Network Approach To Speech Classification From MEG", 
		long_description	: "<h2> Neural Network Approach To Speech Classification From MEG </h2><p> As part of my B.a.S.C in Engineering Science, I completed an undergraduate thesis project, supervised under <a href=‘http://www.cs.toronto.edu/~frank/’>Professor Frank Rudzicz</a>. The goal of the project was to use raw magnetoencephalography (MEG) to train a neural network to classify between four different speech tasks in an effort to better understand the relationships between the brain and speech. </p><p> I was able to develop a model that showed some evidence of ‘learning’ various brain features while being trained on only on raw data, without much data preprocessing. This model may be able to be extended to help better understand research the relationship of the brain with speech using raw MEG without the bias of expert knowledge. </p><p> You can find a copy of my final thesis report <a href=Thesis_Final_Report.pdf> here </a></p><p> <strong>Skills Developed: </strong> Machine Learning Research, PyTorch, Neural Networks, MNE</p> "
	},
	{	id					: 3, 
		title				: "YNCN Digital Team",
		images				: ["images/yncn.png"],
		date 				: "April 2018 - March 2019",
		short_description	: "Modernizing The Website for U of T’s Largest Student Club", 
		long_description	: "<h2> Modernizing The Website for U of T’s Largest Student Club </h2><p>You’re Next Career Network is U of T’s largest student run organization, that focuses on providing sorely needed career related services to the students at the university. It has been running resume workshops, career fairs, and more for over 10 years, bringing in around 200 employers to campus, and hosting over 5000 students at events throughout the year. After spending two years on the team running events, I turned my sights to the tech team because the website was a major pain-point despite having 60,000 yearly page views. It had many issues, including an outdated look, confusing navigation, and a lack of utility.</p><p> My co-lead and I put together a team of 5 volunteer student developers and 2 designers, as well as 2 content developers with the goal of improving the website and providing value to students. We met with various stakeholders to establish requirements, develop technical specs, and started rebuilding the website and adding more services. We redesigned the website to have a more modern feel, and added a more visible featured resources section that can be managed to provide topical resources, improved the user experience of the events calendar, digitized the career fair guidebooks to be put onto the website, and automated many processes for updating content on the website (such as updating the calendar, or adding attending companies to the website).</p><p> I believe we created more value on the website, and the analytics backed up this belief, with a reduced bounce rate from 73% to 40% during the peak week (the week of career fair). The average session duration increased from 1m04s to 1m55s, an increase of 80%, and increased the total number of page-views by 73%, while unique sessions only increased by 5%. Most importantly, the team of volunteers all developed their own skills as developers, and developed long lasting relationships, which is something that I love to see as a lead.</p> <p> You can view the website at <a href=‘www.yourenext.ca’> this link </a></p><p> <strong>Skills Developed: </strong> DevOps, Project Management, Leadership, Python (Flask) + Jinja</p>"
	},
	{	id					: 4, 
		title				: "Amazon Internships",
		images				: ["images/amazon.jpg"],
		date 				: "Summer 2017, Summer 2018",
		short_description	: "Two Summers at Amazon", 
		long_description	: "<h2> Two Summers at Amazon </h2> <p>Two summers in a row, I worked as a software engineering intern out of the Seattle office, during which I improved my skills in writing quality code, and best practices for working in large organizations.</p><p>The first internship, I worked on the Consumables personalization tea, working on projects to improve how customers on Amazon recieve personalized recommendations to help find what they are looking for. During my second internship, I worked on the Alexa music team, where I worked on internal tools to improve how the team handles tickets and issues, drastically reducing the amount of wasted time dealing with repetitive tickets, and increasing the output of the engineering team</p> <p> The difference between writing code for a personal project, or a small team is very different from the quality and rigor needed for code being used by tens of thousands of people if not more. These internships gave me perspective and helped me develop awareness for these coding best practices, as well as the confidence in my own technical abilities to execute at scale.</p><p> <strong>Skills Developed: </strong> Java, AWS (DynamoDB), Building at Scale</p>"
	},
	{	id					: 5, 
		title				: "Internship at Evichat",
		images				: ["images/evichat.jpg"],
		date 				: "Oct 2017 - April 2018",
		short_description	: "Winning the Legal AI Challenge", 
		long_description	: "<h2> Winning the Legal AI Challenge </h2> <p>After my first internship at Amazon, I wanted to experience what it would be like to work in a company that was the polar opposite of Amazon. I found an opportunity to work at Evichat, a legal tech startup that had only 2 full time employees and 1 intern at the time of joining. While at Amazon, I had the luxury of having enormous amounts of support, with incredibly smart people who's job it was to build tools to make my job easier. At Evichat, it was different because I needed to figure out everything on my own. There were no beautifully document Wikis, or internal forums to ask for help on very specific problems. At Evichat, I still had the opportunity to flex my engineering muscle, but there was also a large challenge in being completely independent and building something from the ground up.</p> <p> Part of my job during this internship was to work on the AI component of the product to be a part of the Legal AI Challenge. It was a challenge getting a fully functional AI product working well enough for use. Building a small scale model in class or for small projects is one challenge, but having it productionized, especially without the support of an organization like Amazon was a particularly hard challenge. After months of hard work, we won 1st place in the competition, and it taught me valuable lessons in what it takes to truly build something from the ground up with little support.</p> <p> You can find an article about the win <a href='https://betakit.com/evichat-wins-40000-top-prize-at-legal-innovation-zones-ai-challenge/'> at this link here </a></p> <p> <strong>Skills Developed: </strong> Ruby on Rails, PostgreSQL, GloVe, NLP</p>"
	},
	{	id					: 6, 
		title				: "ENLight Hackfrence",
		images				: ["images/enlight.jpg"],
		date 				: "Nov 2016",
		short_description	: "Pitching an Idea to Kevin O'Leary", 
		long_description	: "<h2>Pitching an Idea to Kevin O'Leary</h2> <p>This Hackfrence was a 24h competition that combined a pitch and a hackathon into one event, with the panel of judges including Kevin O'Leary. Part of the challenge was having so little time to do everything required for the pitch and having something working on the tech side.</p><p>On the tech side, we wrote a Python script that utilized Googles Cloud Vision API to do real-time sentiment analysis on a video feed of an audience. One important aspect that received positive feedback about was how the demo was straightforward and easy to appreciate what was going on. This showed me the value of keeping things simple and approachable. Sometimes, the best solution is not the most techincally challenging solution.</p><p><strong>Skills Developed: Python, Google Cloud Vision API, Presentations</strong></p>"
	},
	{	id					: 7, 
		title				: "AER201",
		images				: ["images/aer201.jpg"],
		date 				: "Jan 2016 - April 2016",
		short_description	: "Building an Autonomous Robot From Scratch", 
		long_description	: "<h2>Building an Autonomous Robot From Scratch</h2> <p>AER201 is a design course that all second year engineering science students take. In this course, we were tasked to build and program a robot mostly from scratch in groups of three. In addition to the technical engineering skills I learned while building and desinging the robot, this was the first time that I had to rigorously plan long term to design and build this robot, as well as document the many engineering design decisions made during such a project.</p> <p> <strong>Skills Developed: Building ICs, Soldering, Circuit Design, Engineering Design Reports </strong></p>"
	},
	{	id					: 8, 
		title				: "Engineering Prank",
		images				: ["images/christmas.mov"],
		date 				: "Dec 2014",
		short_description	: "Building an Christmas Carol Singing Machine", 
		long_description	: "<h2>Building an Christmas Carol Singing Machine</h2> <p>As a prank, a group of first year engineering students decided to build a clocktower that would play various christmas carols on the touch of various buttons. While I did not have much experience with Arduinos or designing circuits, it was both an incredibly exciting project because it felt like one of the first times I was able to build something using engineering skills and planning. In addition, it was a lesson in how to self-learn technical skills for a practical application.</p> <p> <strong>Skills Developed: Building ICs, Soldering, Circuit Design, Self-Learning </strong></p>"
	},
]
